Medicine creation
kgurda/PillWise pull request #3
Opened 2024-12-23 08:44 UTC by kgurda

2024-12-23 08:46 UTC, kgurda commented on app/src/main/java/com/example/pillwise/feature/medicine/presentation/CreationScreen.kt
> +package com.example.pillwise.feature.medicine.presentation
Im not sure how the file structure should look like. I have multiple views - CreationScreen and ListScreen which uses the same MedicineViewModel (and inside it it uses the same MedicineRepository). Does it sound good? Or should I refactor something or add another view model for ListScreen?

2024-12-23 11:33 UTC, Belhaver1993 requested changes

2024-12-23 11:33 UTC, Belhaver1993 commented on app/src/main/java/com/example/pillwise/feature/medicine/presentation/ListScreen.kt
> +        medicines.addAll(medicineList)
It shouldn't work like that. You should only listen to flow of data from the viewModel. I will write another comment there to indicate how it should be done.

Views should only listen to states!

2024-12-23 11:33 UTC, Belhaver1993 commented on app/src/main/java/com/example/pillwise/feature/medicine/presentation/ListScreen.kt
> +fun ListScreen(
You should create another composable in this file with direct access only to uiState and maybe few parameters and lambdas (like in `LoginScreen`). Similarly in `CreationScreen`

2024-12-23 11:33 UTC, Belhaver1993 commented on app/src/main/java/com/example/pillwise/feature/medicine/presentation/ListScreen.kt
> +fun MedicineRow(medicine: Medicine) {
Maybe `MedicineItem`? `Row` suggests it's more than one time here :)

2024-12-23 11:33 UTC, Belhaver1993 commented on app/src/main/java/com/example/pillwise/feature/medicine/presentation/MedicineViewModel.kt
> +
`uiState` for `MedicineListViewModel` should be initialised here, and `uiState` should contain `List<Medicine>`.

```
init {
    medicineRepository.getAll()
        .onEach { medicines ->
            _uiState.update { it.copy(medicines = medicines) }
        }
        .launchIn(viewModelScope)
}
```

But this approach requires that `medicineRepository.getAll()` returns `Flow` :)

2024-12-23 11:33 UTC, Belhaver1993 commented on app/src/main/java/com/example/pillwise/feature/medicine/presentation/MedicineViewModel.kt
> +                val currentState = _uiState.value
You can replace it with `val currentState = _uiState.updateAndGet {` and with isLoading copy here

2024-12-23 11:33 UTC, Belhaver1993 commented on app/src/main/java/com/example/pillwise/feature/medicine/presentation/model/CreationUiState.kt
> +    var isExpirationDateValid: Boolean = true,
Maybe extract validation into one data class?

2024-12-23 11:33 UTC, Belhaver1993 commented on app/src/main/java/com/example/pillwise/feature/medicine/presentation/model/CreationUiState.kt
> +    var capturedImage: Bitmap? = null,
What is the difference between `photoUri` and `capturedImage`?

2024-12-23 11:33 UTC, Belhaver1993 commented on app/src/main/java/com/example/pillwise/navigation/BottomNavigationBar.kt
> +            PillWiseTopLevelRoute(R.string.creation, Icons.Default.AddCircle, CreationRoute),
Maybe creation dialog should be opened on floating action button click? https://developer.android.com/develop/ui/views/components/floating-action-button

2024-12-31 08:34 UTC, kgurda commented on app/src/main/java/com/example/pillwise/feature/medicine/presentation/model/CreationUiState.kt
> +    var capturedImage: Bitmap? = null,
`photoUri` should be removed

2024-12-31 13:35 UTC, kgurda commented on app/src/main/java/com/example/pillwise/navigation/BottomNavigationBar.kt
> +            PillWiseTopLevelRoute(R.string.creation, Icons.Default.AddCircle, CreationRoute),
sounds good!

2025-01-02 09:17 UTC, Belhaver1993 approved these changes
Approving with one small suggestion :) Good job!

2025-01-02 09:17 UTC, Belhaver1993 commented on app/src/main/java/com/example/pillwise/feature/medicine/creation/presentation/MedicineCreationScreen.kt
> +            readOnly = true,
If you want to disable textField entirely, maybe it's worth to display it not as a TextField, but something different? Row with icon and normal text? But it's up to you :)

2025-01-02 10:29 UTC, merged